package com.ce.service.dao;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.ce.service.domain.BusinessCategory;

/**
 * Implementation of Business Methods related to entity BusinessCategory. This (empty) class is generated by mardao, but edited by
 * developers. It is not overwritten by the generator once it exists.
 * 
 * Generated on 2012-12-10T18:01:23.493+0700.
 * 
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class BusinessCategoryDaoBean extends GeneratedBusinessCategoryDaoImpl implements BusinessCategoryDao {

    private final static Logger LOG = LoggerFactory.getLogger(BusinessCategoryDaoBean.class);

    /**
     * Init the important data
     */
    public void init() {
        LOG.debug(">>>>>>>>>>>>>>>>>>>> init business category");
        BusinessCategory category1 = new BusinessCategory();
        category1.setCatKey("restauce");
        category1.setCatDesc("Restaurant");
        this.persist(category1);

        // Taxi
        BusinessCategory category2 = new BusinessCategory();
        category2.setCatKey("taxice");
        category2.setCatDesc("Taxi");
        this.persist(category2);

        // night club
        BusinessCategory category3 = new BusinessCategory();
        category3.setCatKey("nightclubce");
        category3.setCatDesc("Night Club");
        this.persist(category3);
    }
}
