package com.ce.service.dao;

/**
 * Business Methods interface for entity BusinessDetails.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2013-01-25T08:57:09.070+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface BusinessDetailsDao extends GeneratedBusinessDetailsDao {

	// TODO: declare your Business Methods here
	
}
