package com.ce.service.dao;

/**
 * Business Methods interface for entity CommunicationOption.
 * This interface is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-12-10T18:01:23.493+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public interface CommunicationOptionDao extends GeneratedCommunicationOptionDao {

	// TODO: declare your Business Methods here
	
}
