package com.ce.service.dao;

/**
 * Implementation of Business Methods related to entity CommunicationOption.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2012-12-10T18:01:23.493+0700.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class CommunicationOptionDaoBean 
	extends GeneratedCommunicationOptionDaoImpl
		implements CommunicationOptionDao 
{

	// TODO: implement your Business Methods here

}
